CREATE TABLE `rdline` (
	`id` INT(32) NOT NULL AUTO_INCREMENT COMMENT '主键id',
	`rd_name` VARCHAR(50) NULL DEFAULT NULL COMMENT '道路名称',
	`line_classify` VARCHAR(50) NULL DEFAULT NULL COMMENT '线段分类',
	`rd_line` VARCHAR(50) NULL DEFAULT NULL COMMENT '道路线段',
	`qhs_type` VARCHAR(50) NULL DEFAULT NULL COMMENT '桥涵隧类型',
	`car_direction` VARCHAR(50) NULL DEFAULT NULL COMMENT '车行方向',
	`roadbed_width` VARCHAR(50) NULL DEFAULT NULL COMMENT '路基宽度',
	`gc_number` INT(10) NULL DEFAULT '1' COMMENT '共线数量',
	`rd_left_right` VARCHAR(50) NULL DEFAULT NULL COMMENT '线路左右',
	`rd_code` VARCHAR(50) NULL DEFAULT NULL COMMENT '线路编号',
	`mrd_name` VARCHAR(50) NULL DEFAULT NULL COMMENT '主线名称',
	`mrd_begin_name` VARCHAR(50) NULL DEFAULT NULL COMMENT '主线起点名',
	`mrd_end_name` VARCHAR(50) NULL DEFAULT NULL COMMENT '主线终点名',
	`begin_station` VARCHAR(50) NULL DEFAULT NULL COMMENT '起点桩号',
	`end_station` VARCHAR(50) NULL DEFAULT NULL COMMENT '终点桩号',
	`total_length` VARCHAR(50) NULL DEFAULT NULL COMMENT '统计里程',
	`tech_grade` VARCHAR(50) NULL DEFAULT NULL COMMENT '技术等级',
	`high_speed` BIT(1) NOT NULL COMMENT '是否一幅高速',
	`lane_classify` VARCHAR(50) NULL DEFAULT NULL COMMENT '车道分类',
	`rd_surface_materials` VARCHAR(50) NULL DEFAULT NULL COMMENT '路面材料',
	`rd_surface_width` VARCHAR(50) NULL DEFAULT NULL COMMENT '路面宽度',
	`design_speed` INT(16) NULL DEFAULT NULL COMMENT '设计时速(KM/H)',
	`build_time` INT(10) NULL DEFAULT NULL COMMENT '修建年度(YYYY)',
	`rebuild_time` INT(10) NULL DEFAULT NULL COMMENT '改建年度(YYYY)',
	`chain_scission_classify` INT(16) NULL DEFAULT '0' COMMENT '断链分类',
	`urban_road` BIT(1) NULL DEFAULT NULL COMMENT '是否城管路',
	`dead_end_highway` BIT(1) NULL DEFAULT NULL COMMENT '是否断头路',
	`toll_roads` BIT(1) NULL DEFAULT NULL COMMENT '是否收费路',
	`maintenance_length` VARCHAR(50) NULL DEFAULT NULL COMMENT '养护里程(KM)',
	`can_green_length` VARCHAR(50) NULL DEFAULT NULL COMMENT '可绿化里程(KM)',
	`have_green_length` VARCHAR(50) NULL DEFAULT NULL COMMENT '已绿化里程(KM)',
	`through_landform` VARCHAR(50) NULL DEFAULT NULL COMMENT '途径地貌',
	`culvert_number` INT(12) NULL DEFAULT NULL COMMENT '涵洞数量',
	`maintenance_company` VARCHAR(50) NULL DEFAULT NULL COMMENT '管养单位',
	PRIMARY KEY (`id`)
)
COMMENT='道路线段表'
COLLATE='utf8_general_ci'
ENGINE=InnoDB;
